#ifndef AIRLINESCHEDULING_CONSTANTS_H
#define AIRLINESCHEDULING_CONSTANTS_H

#define MIN_NODES 4

#define MAX_LOWER_BOUND 1
#define MIN_LOWER_BOUND 0

#define MAX_CAPACITY_NO_SOURCE 1
#define MIN_CAPACITY 0

#endif //AIRLINESCHEDULING_CONSTANTS_H
